import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "@/ui/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar>
					<Navbar.Item>
						<Navbar.ActiveLink href="/">Home</Navbar.ActiveLink>
					</Navbar.Item>
					<Navbar.Item>
						<Navbar.ActiveLink href="/products">All</Navbar.ActiveLink>
					</Navbar.Item>
				</Navbar>
				<div className="flex flex-grow flex-col">{children}</div>
			</body>
		</html>
	);
}
